"""threads and messages tables created

Revision ID: 4ea8ddfe0dba
Revises: dddec921d129
Create Date: 2025-05-18 17:44:20.646945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ea8ddfe0dba'
down_revision: Union[str, None] = 'dddec921d129'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thread',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_email', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('alternate_id', sa.Integer(), nullable=True),
    sa.Column('product', sa.Enum('CO_PILOT', 'DOC_CREATOR', 'DEVAS', 'MERMAID', 'AGENTIX', name='fynixproducts'), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('last_message_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_thread_user_email_product_is_deleted', 'thread', ['user_email', 'product', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_thread_uuid'), 'thread', ['uuid'], unique=True)
    op.create_table('thread_message',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('parent_message_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('USER', 'SYSTEM', 'ASSISTANT', name='role'), nullable=True),
    sa.Column('display_text', sa.String(), nullable=True),
    sa.Column('is_json', sa.Boolean(), nullable=True),
    sa.Column('is_disliked', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('question_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('prompt_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['parent_message_id'], ['thread_message.id'], ),
    sa.ForeignKeyConstraint(['thread_uuid'], ['thread.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thread_message_thread_uuid'), 'thread_message', ['thread_uuid'], unique=False)
    op.create_table('thread_message_summary',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('thread_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('thread_message_id', sa.Integer(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['thread_message_id'], ['thread_message.id'], ),
    sa.ForeignKeyConstraint(['thread_uuid'], ['thread.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_thread_message_summary_thread_uuid'), 'thread_message_summary', ['thread_uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_thread_message_summary_thread_uuid'), table_name='thread_message_summary')
    op.drop_table('thread_message_summary')
    op.drop_index(op.f('ix_thread_message_thread_uuid'), table_name='thread_message')
    op.drop_table('thread_message')
    op.drop_index(op.f('ix_thread_uuid'), table_name='thread')
    op.drop_index('ix_thread_user_email_product_is_deleted', table_name='thread')
    op.drop_table('thread')
    # ### end Alembic commands ###
