"""Initial migration

Revision ID: 88905aae73ac
Revises: 4ea8ddfe0dba
Create Date: 2025-05-20 12:26:20.591722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88905aae73ac'
down_revision: Union[str, None] = '4ea8ddfe0dba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
