"""local added in enum

Revision ID: dbc2b7e8129c
Revises: 0e18a4bbf053
Create Date: 2025-05-21 11:02:06.968592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbc2b7e8129c'
down_revision: Union[str, None] = '0e18a4bbf053'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE integration_type ADD VALUE IF NOT EXISTS 'local'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
